# Generated by Django 4.1.5 on 2023-01-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creatures", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Behavior",
            new_name="Behaviour",
        ),
        migrations.RenameField(
            model_name="behaviour",
            old_name="behavior",
            new_name="behaviour",
        ),
    ]
