# Generated by Django 4.1 on 2023-01-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='apellido_1',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='nombre',
        ),
    ]
