# Generated by Django 4.1.5 on 2023-01-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta_texto", models.CharField(max_length=200)),
                (
                    "fecha_pub",
                    models.DateTimeField(verbose_name="fecha de publicación"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eleccion_texto", models.CharField(max_length=200)),
                ("votos", models.IntegerField(default=0)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="encuestas.pregunta",
                    ),
                ),
            ],
        ),
    ]
